name: fenics
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx==0.9.0
  - pip>=20.1
  - matplotlib==3.7.1
  - scifem
  - pip:
      - sphinx_book_theme==1.0.1
      - sphinx==6.2.1
      - sphinx-design==0.4.1
