name: festim-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib==3.7.1
  - pip>=20.1
  - sphinx==7
  - folium
  - numpy==1.24
  - sympy
  - sphinx-book-theme
  - sphinx-design~=0.5
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - pillow
  - sphinxcontrib-images
