name: Documentation test

on: [push, pull_request]

jobs:
  docbuild:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
          activate-environment: festim-docs
          environment-file: docs/example-environment.yml

      - name: Doc Tests
        shell: bash -l {0}
        run: sphinx-build -b doctest -d build/doctrees docs build/doctest